dist: xenial   # required for Python >= 3.7
language: python

stages:
- install
- test
- name: deploy
  if: tag =~ tdvt  # only tags with tdvt will allow deploy

install:
  - pip install -e tdvt/

script:
  - cd tdvt/test && python tdvt_test.py -v CommandLineTest ConfigTest DiffTest PrintConfigurationsTest

jobs:
  include:
   - python: 3.7

   - stage: deploy
     python: 3.7
     script: cd $(bash before_deploy.sh)
     deploy:
     - provider: pypi  # dev
       user:
         secure: "rXq+U7a7XG2GGhXPdW3s7pL6N/cMigeddT5gW3yRpj3AH3v354D/rbmqvi8LE60xhVxfnZ68rRGKvNbGLcC64CSvwvXkYsu3l+zeHccD4dHbzvCsLlAlWS6yCk4876RtDvpdnN1Y94avbvA7oITGHLbJy/aOBtq9Q8Oq2NnVA/IX0MUEI3W1tzqYHmMC5I642L5XYSwwCyw8fFm3/NoQFEDcppS6MRn6LJB69XPO78JBne1Ll4IO/XqXlqryGgzA+Ir1VvH3Yp+MntloiV4BwgR6eRUKeSbLUAMD42nOxUmACHlznptZptm0GDY1ktHiKX0yFtySAqd4gK9iiMF13bRNqjTukLsCCjfHFWYZOb2vJI0H49pt2Lx1r1W+nyFGhePuxLxmOj4E3RHbkQmkG8BfokVKtdAHRlzeuIE23i1LJpKU4hvr024mKMYK4TFRwsqOjk+J/FJOu+ocVL4ywEOEulAx/vjKCvDYg4h3P23i9/RR5aJ5j7yGbtZNs0bI3vAKfYekJHOzHeZX9rj40QOLQocDI0kALVVjfxTZvpijPa8lmAFxp0y4btDJeg4REYvglFMbVL60G4mS/NkwJCRdqOoTpSb8C2QUBkbaCVAqqbt42kFVoa3eA9R92gr6Nl0gxv6WtD8pK7ue97rH2JSgrp1Pd2wwktd8ELILb7Q="
       password:
         secure: "oLtM6oiVnq/n6caJCnMOIblyvPsvANfVOwjkR+4yLmFUr9WlVynywgrWDxJGG28l/hLpGd3vn91TiVfiS4apiB2oU6O9AgW+SlKR9lnRr2xTnQAGhT+RpX5ekrItO3rWcQDQRR9+Ds/Nc8bk9MBbn6iuApWaU6G1q9eWiwod5XC0VOeBJ1WgOIR4u3fC2rmR8BUtOwwOz3kDxGxOkgXPunMP/FzatLaZLdwwVIoIAgli/zFvZr26chz58a65+CuozlCBwhvlo+FKmxJjLvk1xDrKNCxaN8KksstZtmeyUFfxoVKxiaoFI3+G9UwXejI2jlwsVzpyhDcJA4gV0mb/xwZlXh/NpA4fRqOsvw1Xn/HXarG/SD2FCvml88oTYQpKjRB8MBEyMNf35lrR5SyGmNI5jk6wA9Z+NFb2qeMcnpkjlp9VrT/8NCdDRMXIU8SQN7WnusrZfUIaX0g0vR2Am8NIik5sAFuT3bWVqFKt+8EcKFW+0PgXXl35UFobNVnrBa21iclqyBFcpoaMeVShssq/cabQbEwgK35YmCRhBDDG91aq5K/cuTPLpLY4rWoyqj/AZV3YD4GvLGBHJ5ep//1K7NSqiu1bmzVEwnb+406XpF2PbMMkSaItrVj1sn5qlfahIqmkT6nXVbBrEyogplsqrMW9LXi6LVXxW5SuTyI="
       server:
         secure: "Z5JbpYqmRvWpiALNeOc71xix3h2O+GiFgHLheC6d73MlL4LdrCJ2Jyq2hz/TX5xFlNO16tvq2aOhOuARPxlV9JBby6p/4vwLlMMYmRTYf51zOXI+lY2P1uvHlUIcpHNM+hP+5bGPcknd2QQPAVKscE70SzVquCHALvN/uDC47H/6T0eoe7sRnA93qd55i/26VuELWYQTSCFCSQDZ0Zjbf+VRx+nU5mRe9NqiTBp3YVHwwhkpAqO06irrm1N+WyAeCRZAFw6lw26xsVb75mVGP5jfnoMri3uAvPXchNUgSsFqIcFiFtjWG+cEuYM/xGY9sNUzYJhPyAD6qAKM0grWXbBeHYWly0FRQp7WmB0XiSC3jgQG87NM4J6vReAt8zXQRfvh46VOr+0q5y7EvO92+8M1Z8O1WqjPRSDIjzPvJ9s+LLKY7sdgMCBYJPwauwUCDQCfyvP1fjOD/Gxc4a5zcsNyKc8JV9ucINUVMKapH0ViUjqPr3cBaX1M5Hjla+1qiprfXWmebRtiw2T6icEbdKi6ib8FSzm+vkMVwNGPgVfs9BgkdWJvY6jhr5a8PgoDKjIiYXSpOc5PE3Ohb68J3cQLumVMUIBsm+/4pUyxHICTiMLyhdfRKrk3cIyH35vgddI5ilmi64ANTfXrFPhU34/pmD55DuzwVeqzwOlxhzU="
       skip_existing: true
       on:
         tags: true
         all_branches: true
     - provider: pypi  # prod
       user:
         secure: "rXq+U7a7XG2GGhXPdW3s7pL6N/cMigeddT5gW3yRpj3AH3v354D/rbmqvi8LE60xhVxfnZ68rRGKvNbGLcC64CSvwvXkYsu3l+zeHccD4dHbzvCsLlAlWS6yCk4876RtDvpdnN1Y94avbvA7oITGHLbJy/aOBtq9Q8Oq2NnVA/IX0MUEI3W1tzqYHmMC5I642L5XYSwwCyw8fFm3/NoQFEDcppS6MRn6LJB69XPO78JBne1Ll4IO/XqXlqryGgzA+Ir1VvH3Yp+MntloiV4BwgR6eRUKeSbLUAMD42nOxUmACHlznptZptm0GDY1ktHiKX0yFtySAqd4gK9iiMF13bRNqjTukLsCCjfHFWYZOb2vJI0H49pt2Lx1r1W+nyFGhePuxLxmOj4E3RHbkQmkG8BfokVKtdAHRlzeuIE23i1LJpKU4hvr024mKMYK4TFRwsqOjk+J/FJOu+ocVL4ywEOEulAx/vjKCvDYg4h3P23i9/RR5aJ5j7yGbtZNs0bI3vAKfYekJHOzHeZX9rj40QOLQocDI0kALVVjfxTZvpijPa8lmAFxp0y4btDJeg4REYvglFMbVL60G4mS/NkwJCRdqOoTpSb8C2QUBkbaCVAqqbt42kFVoa3eA9R92gr6Nl0gxv6WtD8pK7ue97rH2JSgrp1Pd2wwktd8ELILb7Q="
       password:
         secure: "igXt2BrAm/G8pFKZWBKJjEmQoYC9jKxsLJt+WASn5T8XqeeXp6ckEYaP0GkU67S1f3QnZpY5UCrspOU2RbwWMptmiFWrOhHzIFe3hmLzBBeDuGKEPEDo8LijiCBmBMnc3hadewP8fjjxxLJOcip6QOSLNRulr/5QqOTWLcecMhl83Oy+JQp8ZFOr9rRWHFG8EYny/i7eaHR8lYPccv9t7BK2a+K9J0fl2fLqF+MUzK/BE7530UtIZLwVQ08gvWfo6mHi23cfk9cncrjj8O1G3fN65eRClD514M39v4Eak+KKjOvRFSnpoz8q7vdiCPkTnD58hBYm91db91dr8qpkPq/u5iq9Y06yG/59/kZqyA2ro4Uov/hJDaZR/BFFT8rsbU7jlbjCCuJfGLzemCWA4846NoKeIGQDeeX/57yDAHlgBipc4iVMqk1fnuDNQpO+bZ0gJUSX1q2VpzDrkcj8UOARRPyTUV4MhmjBOlF1qX1aEf7gEcXC3x5hNYJHP8r3b9cuSn20ozY06xfZGGIBwI0G9TRSImb6Y/N7wK7164LpAgEm0egXSqJSFsDupOf6NouQi98rGDhw015C7LnBQeiDaETqX+1HQnhvQNNiFLNa9GPLKw2yg7G7BUsynDsFZRug9sFYbALzi6U0GNbWOqs+O3TFfEpvKozDQB0lS28="
       server:
         secure: "BU53tcga8xfTI0oBc6/axzFXEa8WTaqN/T6WSWnxcqQwwUdMa9SjxxkUmi36m4jCyyXihUPYfLQFKg0f2AQ7Ped0ioVAreybRN8afgjVgVXqwmO/GMwQh3yHBRPkfTKJPWq4l522a2vev62V/SbzwIoT4qwSQS9q/BD7GEtuiTjEf99VjQ57PBunExc5N3/afNUau+xQ8H+BLRDCsdYvF5xbOkJ7EwnSCESdAqjl7UGduhhY0/IUFuxtzHNpv6RiW4Sx2pGW1jP89RvNDRRZk/dXn+/KZc7rmxUvAjDJ9SR5YDcxyWiIsdkyJWKtyNGlfno4RAb+Wyj08JeMKvM/d2RIQmeWLVSqpIJg2HCi3Z6yMqPveY7EiRB0lspd5D3uByT258iCw06e9/aIXet1mU3okfCs/4oCNjIJGs7Hoh+5moELIkPDsJIZp4sv1D4VLaRiSPsvLGSVuKirdi1Sd9/dJeCrJVMhozjLGa0tB3qUJpD3QjSpL3eYw1lXY9S8rhL4frd2g5af+JgT6FKL6FJ6RWmUpK8QHQI19737AJfrClJ6YhMJ6ORwNohzQ41TfQlhicm1fa+Z/6coVALWkA8GOe2QQvC3w9q/h6lIE/F+CYvm+gKo12bJ60gHWbOE4nynO0d6CZNcMQj5p5fgU9/jY0ZQzWCcDE+2SdJZquk="
       skip_existing: true
       skip_cleanup: true
       on:
         tags: true
         all_branches: true
