dist: xenial   # required for Python >= 3.7
language: python

stages:
- install
- test
- name: deploy
  if: tag IS present

install:
  - pip install -e tdvt/

script:
  - cd tdvt/test && python tdvt_test.py -v CommandLineTest ConfigTest DiffTest PrintConfigurationsTest

jobs:
  include:
   - python: 3.4
   - python: 3.5
   - python: 3.6
   - python: 3.7

   - stage: deploy
     python: 3.4
     script: cd $(bash before_deploy.sh)
     deploy:
     - provider: pypi
       user:
         secure: "Cl0P8yEF+GzM2saBVrCXOLqdBvf05UemsrJB/lW5yDtVRKYHc3OeFwHWRRpCRT7R57NQrrjeLYamhARM4TBG6/qzA1+wyIekarkyvhu16ZwLArng6/3397kgcRiu7FgTZY9G3glpKawAnh4xhjKC3If/O+WlHKFXDC2GdqLRWgdOyrQrL3QECOthXNzvO0ffLvBXzrazSHBQUfY6W4Rb065VjnZaVmwBWJJ7cu14tk7F0Xde2voOXpNryr/U0C7XbwGZ37qnBtw80fxPlpesJYtEj55FhPgELUx+lyl7YGVtifpbR5tp28jp73Pxh+yOBuEAl5gcCDY3npNeIH0RpO8amM9Txpx0uUr2TFkprRva5y1hE3gwkhWjFHPlfETHveWjQKMO+10m1NqtyyDi21j5q/7clfU/rJJm18fp5wf6PP7nSUuX6xA2doxh3z+3JvKJPEovaqlmRtokcr0htgOeYARE5erTg8XXGszQaJZEx52/G6CX60S33XPTXz6I2adpFqLLPNzpcvF99AsQSdbi9mc1xv+EMe+nLwu6m6xSeMpiONF2rhWWr0QdDloZhDVAVvdv9kj6jaC3tcjM5fReb95y/Q9k0PDMSHEQksfgqZP2tDu6un0ukxwtI0RMnXiPlqGBSHdpBJifw9thLQyIO6BjgskdltQq3DPE6Rk="
       password:
         secure: "YyHIDbT2KFF7Anlh7FilFyXMCAWbJBZJBafx+GrpmFiqRajHIDBu5DthzTooF/HuNpAQMqqjz1/7r5ASDwJEK9/a3yzwM7b+HTq6BIBia998ziUJTvmTCvVUibXx+Cs9YR1yBKf5TE0ct/TbJf73AT2BitK3tloMkbYMB4WLxhQD4du5GhdSfPTu23uw3WmUe7mswhcHJvjozj09UQkuBc5iWUkCKYQeL49fsYrBjMnf1MRIUe4wvLeA2lXwiiRva62t0j+5tyCPC521HGgolNMH2zsS/HjMojYN9jSZbNQK5OBtySC4d7AUfOQlRV0rSvD9vtpKdlMpsHzyeogN7yZp7/+5bX2tVUYkAS3Sj3vNJnlGIDHnbH7f276N8gIa1lobqZCZjFyBzw1CHGl31lZyuD5Hcjb9N+EknvuRZBPSPqdSbqzVxFcpGtZOim+vYusEbq2xZP+ox2q+BUWBJKWPClsFZzV82CmPaYGrtmmnT1tKh7Cd+6xnEVgz9lGLGsl1SSDISsuZhqeyIKHFftVCjbQ6OhWFL14jI3ww5pJFG4MM5o4q7PA/SmDkdZ8GbefQgcaj3/5G+BjVCklS0uljTgibcrbrN1bSq9G4DoYtYG76qIvHs+Y+dhPHGBA/3eYt+PB1RwBK95iSEhHL2TvjoMwNMoPa8TeHN+tXQBc="
       server:
         secure: "Z5GQsnAMf3lKR5zDxZG6FlOASrr14dceOA1dXp2kkccEufPZqc+mxsW2zdNIzgZMs8ZiTnFKL106iOaK0GhAxUbMRl4tJ41lhXFziP5cntR4jYxcKKFIfDWT+v4H+3fmqX7US+UM0Ot6Kfk/lMEE8VxjMhtP+XWwVUA+AeJRsKQkqtTYa0QWeH3n77czbxcmHR3C8KNyKVtwPHPxJ9bjwsSWmVE2RJpUgh0Snef0pwq+A2G3T4tHhOU0akQ/nl4mPgSDGdCD3W9WzyRGA2in4R9BM0KJdpcV3GojKmb7aoDzVu1XbHYff10KKn9We/9V52dS2lglvAU2/frOTf1Uo8i1Ptg4i3VOlL4lIyCtuHPGI5GWGnY3gRwWu3RdB2D6WJ8I4ZcRr6UDr5BbEW92dXpJXhhVYw7fGNUrRaciZYM9LsejbFeabv79Bm+9XFJVHx5nEOr5zc2ouodNHAufk+U+2VQ6hGZ2yrLPMBpqSFPvEvcZsRcz/Sxb28BHaZrSa9AW21Qhsk2DKU3BrZShuFHjvFxa3hwK5FEZ5OSVUm8grGY25M8WPd/ExorN6kVs2FMmBNs8if98gOXBU8C5upwAgfmHEaBENX1U3q+qM2d1pejKgUhE+AMtugEQMdESn1+mI7ujKZNQ/jsjncNDHqxup6ZhG1rZX3ndFEtOogI="
       skip_existing: true
       on:
         tags: true
         all_branches: true
     - provider: pypi
       user:
         secure: "Cl0P8yEF+GzM2saBVrCXOLqdBvf05UemsrJB/lW5yDtVRKYHc3OeFwHWRRpCRT7R57NQrrjeLYamhARM4TBG6/qzA1+wyIekarkyvhu16ZwLArng6/3397kgcRiu7FgTZY9G3glpKawAnh4xhjKC3If/O+WlHKFXDC2GdqLRWgdOyrQrL3QECOthXNzvO0ffLvBXzrazSHBQUfY6W4Rb065VjnZaVmwBWJJ7cu14tk7F0Xde2voOXpNryr/U0C7XbwGZ37qnBtw80fxPlpesJYtEj55FhPgELUx+lyl7YGVtifpbR5tp28jp73Pxh+yOBuEAl5gcCDY3npNeIH0RpO8amM9Txpx0uUr2TFkprRva5y1hE3gwkhWjFHPlfETHveWjQKMO+10m1NqtyyDi21j5q/7clfU/rJJm18fp5wf6PP7nSUuX6xA2doxh3z+3JvKJPEovaqlmRtokcr0htgOeYARE5erTg8XXGszQaJZEx52/G6CX60S33XPTXz6I2adpFqLLPNzpcvF99AsQSdbi9mc1xv+EMe+nLwu6m6xSeMpiONF2rhWWr0QdDloZhDVAVvdv9kj6jaC3tcjM5fReb95y/Q9k0PDMSHEQksfgqZP2tDu6un0ukxwtI0RMnXiPlqGBSHdpBJifw9thLQyIO6BjgskdltQq3DPE6Rk="
       password:
         secure: "ry8BAYxVmIm4TuJRUB69TaZO4v2w1A7XFAYfygtvhewF1uNKrh9ui+T2nR81pPyQUOd8dz97jcY7ErskBoX7fxNMvh0nJdZw5Gs4HNNFpxC7g9OyN6ffRvGOVwcR6LLIfjSdB1R//IlO8qeNnkoQPu2gi4RzOPtzvlczdFL0tZ3VTXYA//v1LunK+OXPADgBDKlTn/k4RAjCtx9jFBSNvb4r+1/EN2wUMKHhjn7gdoLN8UPtaNRqTG76bL6Nf/cbErdAogBed0ArNGtYaG8lc+Gqa9g17d20hwDjWK+5zybeY89E3AKZK7DEzQpCX+3lyaxKtXtxnAu5wc6HrgvwNd0eWsYtiRu0p38cCniDxXTnrQzwC+kSkaxoWfL/mDMvntQ0j4ybNhaSSjs/N367f1l9pTeVFj56NeZn4bhznR30rT5E8YV4VpHEymVgJs6HDNWYzBLxcQgh2M3+LSYmj4HsWXCUrgHRxNQBUPj2rnwTngOFJzEx2QCM5ypcsYoC5zEeHrsGQOcrC8b5PiJ1VspZSb/TYqmFrCF+EaFeppyRbuNA7BMZSX5nKTLxS436X169EjpKq95D6f5nF7SnwHy6pEEgNW/RkBz8haTz2q5/EiGKYW9D60290dGjnreekAk1OVQugXjSjlxUmSibgIzBjVwrKML2I+HzBdGhApU="
       server:
         secure: "O1EDPLPU2O0DIdPU037C2SpaZLrjF8VK8b2AJuni+y1jZUIc3ExLK9MRaLRtQ+0Iot6rkBojYMISxrSHZykCZe4AkW3NsuMjMfZuGcxbybG6MdISieQvIMFZxRdxxletH3hGuUkgumQYQppFc1tcdhjCycl7cQFoN49wZUni0SbVBL6SHUg9J13YpWUrQSUa5l4BH9fNtxuvxKOsskVlIAeGWIqj1KJKfCzvOOsPKjaVL36ephWAFrE8P0kUb69KO+rsX25k7oyO9aptZu0bxc9DShveB3YPjAQYwzgM1QyJ7fFZ9h/C35TazRPaBEbTkJlU4QQtIsw88sOfvzKbZa9dYYyk2Rc1qjDLWHnYjdMipJwdfODmZqtUpG97940CdvsF0kH+E8c90CevS7C/VCTes+hqg6ajcTz81Je8kFgt+Au4vFPdJ199kZQyKoYbLYuPdwpQbPardI0wc9RhNDbLMA1Wqk6fodzhOISbvLPWvX+KMUHeGE2Gb935vVzVvfu2U3BLuuPu8IlB3GChq3cWaFKWTKSGRGV215k5DIfIBgbeXKxGmgD3z6ULSdu+7oXT3iVU0RSEsIScYQ0mcx8jGRtQf1IyLVRSeKPcwKxATRdIedVjGRVZDsouTpla5Bs94C9Ui3Ix0Wq0Q63dmYbbnButoYSxYyDqQ3kbqyY="
       skip_existing: true
       skip_cleanup: true
       on:
         tags: true
         all_branches: true
