name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install TDVT
      run: |
        python -m pip install --upgrade pip
        pip install -e tdvt/ 
    - name: Run TDVT unit tests
      run: |
        cd tdvt/test
        python tdvt_test.py -v CommandLineTest ConfigTest DiffTest PrintConfigurationsTest
    - name: Install Connector Packager
      run: |
        cd connector-packager
        python setup.py install
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['1.8', '1.10', '1.12']
    name: Run Connector Packager unit tests with JDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@master
      - name: ${{ matrix.java }}
        uses: actions/setup-java@v1.0.0
        with:
          java-version: ${{ matrix.java }}
      - run: cd connector-packager && python setup.py test
